name: Run local CI

on:
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Gradle wrapper and caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Print workspace
        run: pwd && ls -la

      - name: Run tests
        run: ./gradlew clean test --no-daemon

  deploy:
    runs-on: ubuntu-latest
    needs: test
    env:
      # RabbitMQ Configuration
      RABBITMQ_VIRTUAL_HOST: /
      RABBITMQ_USER_EVENTS_QUEUE: user.events.queue
      RABBITMQ_PASSWORD: fabd378804334da0
      RABBITMQ_PORT: 5672
      RABBITMQ_DL_EVENTS_QUEUE: dl.queue
      RABBITMQ_DL_EXCHANGE: dlx.exchange
      RABBITMQ_USERNAME: 4cf376fa
      RABBITMQ_MAIN_EXCHANGE: main.exchange
      RABBITMQ_HOST: 172.17.0.1

      # Service Ports
      CONFIG_SERVICE_PORT: 8888
      GATEWAY_SERVICE_PORT: 8080
      AUTH_SERVICE_PORT: 8081
      DISCOVERY_SERVICE_PORT: 8761
      EMPLOYEE_SERVICE_PORT: 8082

      # Database Configuration
      DB_PORT: 5434
      DB_NAME: 5833b5de
      DB_USERNAME: 9228cf35
      DB_PASSWORD: 78f9026b4f7a4580
      DB_POOL_SIZE: 10
      DB_HOST: 172.17.0.1

      # JWT Configuration
      JWT_ISSUER: emp-service
      JWT_SECRET: a41f8d35dea94487b72292ad194effcc
      JWT_EXPIRATION_IN_HOURS: 24

      # Network & Discovery
      NETWORK_HOST: 172.17.0.1
      DISCOVERY_SERVICE_URL: http://172.17.0.1:8761/eureka

      # Git Configuration
      GIT_REPO_LINK: http://172.17.0.1:3001/emp_admin/shared-config.git

      # Application Configuration
      LOG_LEVEL: INFO
      DEFAULT_PASSWORD: 8cdbc1ce865b4676

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Gradle wrapper and caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Bootstrap shared config
        run: |
          ./gradlew --include-build bootstrap :bootstrap:createGitConfig --info -PuseEnv=true --no-daemon
          if [ ! -f default.env ]; then
            echo "::error::default.env was not created"
            exit 1
          fi
          echo "default.env created:"
          cat default.env

      - name: Source default.env and validate variables
        run: |
          set -a
          source ./default.env
          set +a
          
          # List of required variables
          REQUIRED_VARS=(
            "AUTH_SERVICE_PORT"
            "CONFIG_SERVICE_PORT"
            "DB_HOST"
            "DB_NAME"
            "DB_PASSWORD"
            "DB_POOL_SIZE"
            "DB_PORT"
            "DB_USERNAME"
            "DEFAULT_PASSWORD"
            "DISCOVERY_SERVICE_PORT"
            "DISCOVERY_SERVICE_URL"
            "EMPLOYEE_SERVICE_PORT"
            "GATEWAY_SERVICE_PORT"
            "GIT_REPO_LINK"
            "JWT_EXPIRATION_IN_HOURS"
            "JWT_ISSUER"
            "JWT_SECRET"
            "LOG_LEVEL"
            "NETWORK_HOST"
            "RABBITMQ_DL_EVENTS_QUEUE"
            "RABBITMQ_DL_EXCHANGE"
            "RABBITMQ_HOST"
            "RABBITMQ_MAIN_EXCHANGE"
            "RABBITMQ_PASSWORD"
            "RABBITMQ_PORT"
            "RABBITMQ_USER_EVENTS_QUEUE"
            "RABBITMQ_USERNAME"
            "RABBITMQ_VIRTUAL_HOST"
          )
          
          # Validate each variable
          for var in "${REQUIRED_VARS[@]}"; do
            if [ -z "${!var}" ]; then
              echo "::error::Required environment variable $var is not set"
              exit 1
            fi
            echo "✓ $var is set"
          done

      - name: Run Flyway create
        run: ./flyway/create

      - name: Run Flyway migrate
        run: ./flyway/migrate

      - name: Build Docker Compose services
        run: docker-compose build

      - name: Start Docker Compose services
        run: docker-compose up -d

      - name: Wait for services to be healthy
        run: |
          echo "Waiting for services to start..."
          sleep 30
          
          # Check if containers are running
          docker-compose ps
          
          # Check logs for any errors
          echo "=== Discovery Service Logs ==="
          docker-compose logs discovery-service | tail -n 50
          
          echo "=== Gateway Service Logs ==="
          docker-compose logs gateway-service | tail -n 50
